Feature
Vishal30M/Portfolio-setup-mobile-version-Project-change pull request #1
Opened 2022-06-02 21:18 UTC by Vishal30M

In this project I did the following:

- I set up Linters in my Repository.
- I modified the README.md file.
- Added HTML and CSS files.
- I fixed the linter errors.

2022-06-02 21:41 UTC, Lucas-Masaba commented on index.html
> +        <a href="#" class="contact">LET'S CONNECT </a>
- [ ] It would be better if you make this a `hx` tag instead of an `a` tag since it is a heading 🏄

2022-06-03 18:52 UTC, omarsalem7 requested changes
Hi @Vishal30M, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 18:52 UTC, omarsalem7 commented on index.html
> +                </ul>
- [ ] As requested by the previous reviewer use `ul and li` to make a language list but after you made it there issue in your design that your design does not match Figma.
- Your design
![image](https://user-images.githubusercontent.com/53402600/171927987-31c31a99-0c03-4999-b22c-32a1259579ee.png)
- Figma
![image](https://user-images.githubusercontent.com/53402600/171928111-3d25ca6d-85f5-4248-90cc-bb8be627020a.png)

2022-06-03 18:52 UTC, omarsalem7 commented on index.html
> +                <a href="#" class="contact">LET'S CONNECT </a>
- [ ] As mentioned by the previous reviewer, please use `hx` instead of `<a>` because it is a heading and to improve SEO.

2022-06-03 21:07 UTC, algerina approved these changes
Hi @Vishal30M , 
Good job so far! 

May I highlight the following:

- The repo looks professional. :heavy_check_mark: 
- There are no linter errors :heavy_check_mark: 
- You have descriptive :heavy_check_mark: 
- You implemented the changes required by the previous reviewers :heavy_check_mark: 

## STATUS: APPROVED :muscle::clap:
<img src="https://media0.giphy.com/media/FbZYCW78PANyM/giphy.gif"/>

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-06-03 21:07 UTC, algerina commented on index.html
> +                    <h3 >Framework</h3>
- [ Optional] You did well but there's a typo here it should be `Framworks`  instead of `Freamwork`.

2022-06-04 02:24 UTC, merged